# Generated by Django 6.0.2 on 2026-03-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhenInRome", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="image",
            field=models.ImageField(blank=True, upload_to="page_images"),
        ),
        migrations.AddField(
            model_name="page",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
