# Generated by Django 6.0.2 on 2026-03-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhenInRome", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="location",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
