# Generated by Django 6.0.2 on 2026-03-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhenInRome", "0002_alter_recommendation_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="image",
            field=models.ImageField(blank=True, upload_to="city_images"),
        ),
    ]
