# Generated by Django 5.2.7 on 2026-03-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhenInRome", "0002_alter_city_options_userprofile_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review_Views",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
            ],
        ),
    ]
