# Generated by Django 6.0.2 on 2026-03-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhenInRome", "0002_category_remove_recommendation_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image_name",
            field=models.CharField(default="default.jpg", max_length=128),
        ),
    ]
