# Generated by Django 5.2.7 on 2026-03-25 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhenInRome", "0003_review_views"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review_Views",
        ),
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
