# Generated by Django 6.0.2 on 2026-03-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhenInRome", "0003_city_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="image",
            field=models.ImageField(blank=True, upload_to="page_images"),
        ),
    ]
