# Generated by Django 5.2.7 on 2026-03-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WhenInRome", "0004_alter_city_image"),
        ("WhenInRome", "0004_delete_review_views_review_created_at"),
    ]

    operations = []
