# Generated by Django 5.2.7 on 2026-03-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WhenInRome", "0005_merge_20260326_1621"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="pronouns",
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="image",
            field=models.ImageField(blank=True, upload_to="recommendation_images"),
        ),
        migrations.DeleteModel(
            name="VisitedCity",
        ),
    ]
